version: '3.9'
services:
  backend:
      build: ./backend
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./backend:/app
      ports:
        - "8000:8000"
      depends_on:
        - db

  frontend:
      build: ./frontend
      command: ng serve --host 0.0.0.0
      volumes:
        - ./frontend:/app
        - node_modules:/app/node_modules
      ports:
        - "4200:4200"

  db:
      image: postgres:13
      environment:
        POSTGRES_DB: mydatabase
        POSTGRES_USER: myuser
        POSTGRES_PASSWORD: mypassword
      volumes:
        - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  node_modules: