# Generated by Django 5.0.1 on 2024-02-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asanapi', '0002_initial'),
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='completed_lessons',
            field=models.ManyToManyField(null=True, related_name='completed_users', to='asanapi.lesson'),
        ),
        migrations.AlterField(
            model_name='user',
            name='learned_concepts',
            field=models.ManyToManyField(null=True, related_name='learned_users', to='asanapi.concept'),
        ),
    ]
