# Generated by Django 5.0.1 on 2024-02-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asanapi', '0002_initial'),
        ('auth_api', '0002_alter_user_completed_lessons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='completed_lessons',
            field=models.ManyToManyField(blank=True, related_name='completed_users', to='asanapi.lesson'),
        ),
        migrations.AlterField(
            model_name='user',
            name='learned_concepts',
            field=models.ManyToManyField(blank=True, related_name='learned_users', to='asanapi.concept'),
        ),
        migrations.AlterField(
            model_name='user',
            name='left_off_at',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
