# Generated by Django 5.0.1 on 2024-02-20 19:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('data_url', models.CharField(max_length=500)),
                ('level', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_url', models.CharField(default='assets/image-not-found.jpg', max_length=500)),
                ('script_url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('allow_lab_help', models.BooleanField()),
                ('allow_composit', models.BooleanField()),
                ('allow_lab_sharing', models.BooleanField()),
                ('require_min_lab_score', models.BooleanField()),
                ('sequential', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TFModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DataPipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipe_spec', models.JSONField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_pipes', to='asanapi.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public', models.BooleanField(default=False)),
                ('pipe', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab', to='asanapi.datapipe')),
                ('pipe_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_in_labs', to='asanapi.datapipe')),
            ],
        ),
    ]
