# Generated by Django 5.0.1 on 2024-02-20 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asanapi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='shared_with_users',
            field=models.ManyToManyField(related_name='shared_labs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lab',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='recommended_challenges',
            field=models.ManyToManyField(related_name='recommended_in_lessons', to='asanapi.datasource'),
        ),
        migrations.AddField(
            model_name='concept',
            name='conveyed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conveyed_concepts', to='asanapi.lesson'),
        ),
        migrations.AddField(
            model_name='concept',
            name='required_for',
            field=models.ManyToManyField(related_name='required_concepts', to='asanapi.lesson'),
        ),
        migrations.AddField(
            model_name='space',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_in_spaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='space',
            name='shared_labs',
            field=models.ManyToManyField(related_name='shared_in_spaces', to='asanapi.lab'),
        ),
        migrations.AddField(
            model_name='space',
            name='users',
            field=models.ManyToManyField(related_name='member_in_spaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lab',
            name='model',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab', to='asanapi.tfmodel'),
        ),
        migrations.AddField(
            model_name='lab',
            name='model_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_in_labs', to='asanapi.tfmodel'),
        ),
        migrations.AddField(
            model_name='unit',
            name='challenge_choices',
            field=models.ManyToManyField(related_name='choice_in_units', to='asanapi.datasource'),
        ),
        migrations.AddField(
            model_name='unit',
            name='in_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='asanapi.space'),
        ),
        migrations.AddField(
            model_name='unit',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_in_units', to='asanapi.lesson'),
        ),
        migrations.AddField(
            model_name='unit',
            name='linked_labs',
            field=models.ManyToManyField(related_name='linked_units', to='asanapi.lab'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('in_space', 'order_index'), name='unique_unit_order'),
        ),
    ]
