# Generated by Django 5.0.1 on 2024-02-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asanapi', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='name',
            field=models.CharField(default='No Name', max_length=50),
        ),
    ]
