# Generated by Django 5.0.1 on 2024-05-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asanapi', '0003_remove_pipe_pipe_conf_remove_pipeversion_pipe_conf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='data_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dataversion',
            name='data_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dataversion',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
